services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=invojsik'
      - 'POSTGRES_PASSWORD=invojsik'
      - 'POSTGRES_USER=invojsik'
    ports:
      - '5432:5432'

  invojsik:
    image: docker.io/library/invojsik:latest
    build:
      context: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/invojsik
      SPRING_DATASOURCE_USERNAME: invojsik
      SPRING_DATASOURCE_PASSWORD: invojsik
    ports:
      - "8080:8080"
    profiles:
      - invojsik
